# Generated by Django 5.0.3 on 2024-05-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobListings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
    ]
