# Generated by Django 5.0.3 on 2024-04-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/conversation_images/'),
        ),
    ]
