# Generated by Django 5.0.3 on 2024-04-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversationmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='conversation_images/'),
        ),
    ]
